#Config file for S4 simulation

schema: s4_1.1
units: { length: um, angle: deg }

filename: 'results/LWIR_Meta/rect_si_air_d1500_t8000_a4000_angle0-15' # Name of the file to save

lattice:
  a: {value: 4}  # x period (µm)
layers:
  - { name: Top,    thickness: {value: 0.0},   material_key: Air }
  - { name: Pillar, thickness: {value: 8.0}, material_key: Air }   # shapes go here (Air is on background)
  - { name: Bottom, thickness: {value: 0.0},   material_key: Sub }

materials:
  #Examples: 
    # refractiveindex.info  
    #   Si:  { shelf: main, name: Si,  source: Schinke }
    # RIDB
    #   Si3N4: { shelf: RIDB, name: Si3N4, source: Si3N4_LPCVD_low_stress_010925}
    #   name is not important here. Only shelf and source matter.
    # Constant n:
    #   Glue: { shelf: main, name: Glue, source: n=1.46 }
    #   If source is n=value, then constant refractive index is used.
    #   Everything else is ignored. Support only real constant n.
  # Map keys (Air/Meta/Sub) to refractiveindex.info datasets or RIDB
  Air:  { shelf: main, name: Air,   source: n=1 }           # constant
  Meta: { shelf: main, name: Si, source: n=3.42 }          # metasurface 
  Sub:  { shelf: main, name: Si,  source: n=3.42 }          # substrate 

sweep:
  wl:    { lin: [3, 16, 261] }       # start, stop, num (µm)
  theta: { lin: [0, 15, 16] }          # incidence polar angle (deg)
  phi:   { value: 0 }                # azimuth (rad)

shapes:
  main: # name of the shape 
    type: Rectangle # shape type (Rectangle, Ellipse)
    layer: Pillar # layer name where the shape is located
    material_key: Meta # material key for the shape
    center:      { x: { value: 0.0 },  y: { value: 0.0 } }
    halfwidths:  { x: { value: 0.75 }, y: { tie: x } } #for Rectangle: halfwidths, for Ellipse: radii
    rotation_deg: { value: 0 }
  
# S4 parameters
num_basis: 169 # Number of fourier harmonics used to do simulations (13 along x and 13 along y)
num_orders: 9 # Number of diffraction orders to capture 
max_variants: 10000 # Maximum geometry variants to iterate (safety)

# S4 options
S4_options:
  Verbosity: 0 # 0-9
  LatticeTruncation: 'Circular' # Sets the type of lattice truncation to use when selecting G-vectors.                            
  DiscretizedEpsilon: True # Discretization in generating the Fourier coefficients of the in-plane epsilon profiles.
  DiscretizationResolution: 8 # This function sets the resolution of the FFT grid and vector field generated by PolarizationDecomposition.
  PolarizationDecomposition: True # the use of proper in-plane Fourier factorization rules by decomposing fields into a polarization basis which conforms to the material boundaries.
  PolarizationBasis: 'Jones' # Sets the method by which the polarization decomposition basis is generated.
  LanczosSmoothing: False
  SubpixelSmoothing: True
  ConserveMemory: False
