#Config file for S4 simulation

schema: s4_1.1
units: { length: um, angle: deg }

filename: '/home/rodionsa/data/LWIR_filters/Test' # Name of the file to save

lattice:
  a: {value: 4.84}      # period

layers:
  - { name: Top,    thickness: {value: 0.0},   material_key: Air }
  - { name: Pillar, thickness: {value: 2.0}, material_key: Air }   # shapes go here (Air is on background)
  - { name: Bottom, thickness: {value: 0.0},   material_key: Sub }

materials:
  # Map keys (Air/Meta/Sub) to refractiveindex.info datasets
  Air:  { shelf: main, name: Air,   source: n=1.0 }           # constant
  Meta: { shelf: main, name: Si,    source: Franta }          # metasurface
  Sub:  { shelf: main, name: ZnSe,  source: Querry }          # substrate

sweep:
  wl:    { lin: [7, 14, 151] }       # start, stop, num (µm)
  theta: { value: 0 }                # incidence polar angle (deg)
  phi:   { value: 0 }                # azimuth (deg)

shapes:
  rect_main:
    type: Rectangle
    layer: Pillar
    material_key: Meta
    center:      { x: { value: 0.0 },  y: { value: 0.0 } }
    halfwidths:  { x: { value: 1.5 }, y: { value: 1 } }
    rotation_deg: { value: 0 }
  
# S4 parameters
num_basis: 169 # Number of fourier harmonics used to do simulations (13 along x and 13 along y)
num_orders: 9 # Number of diffraction orders to capture 
max_variants: 2 # Maximum geometry variants to iterate (safety)

# S4 options
S4_options:
  Verbosity: 0 # 0-9
  LatticeTruncation: 'Circular' # Sets the type of lattice truncation to use when selecting G-vectors.                            
  DiscretizedEpsilon: False # Discretization in generating the Fourier coefficients of the in-plane epsilon profiles.
  DiscretizationResolution: 8 # This function sets the resolution of the FFT grid and vector field generated by PolarizationDecomposition.
  PolarizationDecomposition: True # the use of proper in-plane Fourier factorization rules by decomposing fields into a polarization basis which conforms to the material boundaries.
  PolarizationBasis: 'Jones' # Sets the method by which the polarization decomposition basis is generated.
  LanczosSmoothing: False
  SubpixelSmoothing: True
  ConserveMemory: False
